---------------------------------------------------------------------------
-- SkillSwap — Database Seed
--
-- Fills the database with feature-complete test data covering every area of
-- the current architecture: profiles, skills, courses, campuses,
-- availabilities, friendships, matching, sessions, gamification, the social
-- feed, notifications and admin moderation.
--
-- HOW TO RUN
--   Local:  the Supabase CLI runs this automatically on `supabase db reset`
--           if `config.toml` points `[db.seed].sql_paths` at this file, or run
--           it manually:  psql "$DATABASE_URL" -f seed.sql
--
-- LOGIN CREDENTIALS (all accounts share the same password)
--   Password: password123
--   Admin:    admin@skillswap.test
--   Students: alice@skillswap.test, bob@skillswap.test, carol@skillswap.test,
--             david@skillswap.test, emma@skillswap.test, frank@skillswap.test
--
-- NOTE ON SKILL LEVELS
--   The live `users_skills.user_skill_level` column is numeric(4,2) in the
--   range 0–10. Learners are seeded around 1–2 and teachers around 7–9 so the
--   `match-students` edge function (which pairs level <= 2 with level >= 4)
--   produces visible matches.
---------------------------------------------------------------------------

do $$
declare
  ---------------------------------------------------------------------------
  -- Fixed auth ids (so the seed is idempotent and re-runnable after a reset).
  ---------------------------------------------------------------------------
  admin_auth uuid := '00000000-0000-0000-0000-0000000a0001';
  alice_auth uuid := '00000000-0000-0000-0000-0000000a0002';
  bob_auth   uuid := '00000000-0000-0000-0000-0000000a0003';
  carol_auth uuid := '00000000-0000-0000-0000-0000000a0004';
  david_auth uuid := '00000000-0000-0000-0000-0000000a0005';
  emma_auth  uuid := '00000000-0000-0000-0000-0000000a0006';
  frank_auth uuid := '00000000-0000-0000-0000-0000000a0007';

  -- Resolved public.users ids (generated by the handle_new_user trigger).
  admin_user uuid;
  alice_user uuid;
  bob_user   uuid;
  carol_user uuid;
  david_user uuid;
  emma_user  uuid;
  frank_user uuid;

  -- Academic levels.
  level_l1 uuid;
  level_l3 uuid;
  level_m1 uuid;
  level_m2 uuid;

  -- Skills.
  skill_javascript uuid;
  skill_python uuid;
  skill_guitar uuid;
  skill_public_speaking uuid;
  skill_spanish uuid;
  skill_photography uuid;
  skill_cooking uuid;
  skill_mathematics uuid;

  -- Campuses.
  campus_paris uuid;
  campus_lyon uuid;
  campus_lille uuid;

  -- Courses.
  course_bachelor_cs uuid;
  course_master_data uuid;
  course_bachelor_design uuid;

  -- Session types (already seeded by migration — resolved by name).
  type_workshop uuid;
  type_quick_course uuid;
  type_club uuid;

  -- Sessions.
  session_js uuid;
  session_speaking uuid;
  session_spanish uuid;

  -- Gamification: badges.
  badge_first_steps uuid;
  badge_team_player uuid;
  badge_knowledge_sharer uuid;
  badge_point_master uuid;

  -- Gamification: point actions.
  action_session_teacher uuid;
  action_session_learner uuid;
  action_challenge_done uuid;
  action_post_created uuid;
  action_friend_added uuid;

  -- Gamification: challenges.
  challenge_three_sessions uuid;
  challenge_five_friends uuid;

  -- Social feed posts.
  post_alice uuid;
  post_carol uuid;
  post_david uuid;
  post_emma uuid;

  -- Matching.
  match_request_alice_bob uuid;
  match_request_david_carol uuid;
begin
  ---------------------------------------------------------------------------
  -- 1. AUTH USERS (+ identities for email/password login).
  --    The on_auth_user_created trigger creates the matching public.users
  --    and public.user_roles rows automatically.
  ---------------------------------------------------------------------------
  insert into auth.users (
    instance_id, id, aud, role, email, encrypted_password,
    email_confirmed_at, created_at, updated_at,
    raw_app_meta_data, raw_user_meta_data,
    confirmation_token, recovery_token, email_change_token_new, email_change
  )
  values
    ('00000000-0000-0000-0000-000000000000', admin_auth, 'authenticated', 'authenticated', 'admin@skillswap.test', crypt('password123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', ''),
    ('00000000-0000-0000-0000-000000000000', alice_auth, 'authenticated', 'authenticated', 'alice@skillswap.test', crypt('password123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', ''),
    ('00000000-0000-0000-0000-000000000000', bob_auth,   'authenticated', 'authenticated', 'bob@skillswap.test',   crypt('password123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', ''),
    ('00000000-0000-0000-0000-000000000000', carol_auth, 'authenticated', 'authenticated', 'carol@skillswap.test', crypt('password123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', ''),
    ('00000000-0000-0000-0000-000000000000', david_auth, 'authenticated', 'authenticated', 'david@skillswap.test', crypt('password123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', ''),
    ('00000000-0000-0000-0000-000000000000', emma_auth,  'authenticated', 'authenticated', 'emma@skillswap.test',  crypt('password123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', ''),
    ('00000000-0000-0000-0000-000000000000', frank_auth, 'authenticated', 'authenticated', 'frank@skillswap.test', crypt('password123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '');

  insert into auth.identities (
    id, user_id, identity_data, provider, provider_id,
    last_sign_in_at, created_at, updated_at
  )
  values
    (gen_random_uuid(), admin_auth, format('{"sub":"%s","email":"%s"}', admin_auth, 'admin@skillswap.test')::jsonb, 'email', admin_auth::text, now(), now(), now()),
    (gen_random_uuid(), alice_auth, format('{"sub":"%s","email":"%s"}', alice_auth, 'alice@skillswap.test')::jsonb, 'email', alice_auth::text, now(), now(), now()),
    (gen_random_uuid(), bob_auth,   format('{"sub":"%s","email":"%s"}', bob_auth,   'bob@skillswap.test')::jsonb,   'email', bob_auth::text,   now(), now(), now()),
    (gen_random_uuid(), carol_auth, format('{"sub":"%s","email":"%s"}', carol_auth, 'carol@skillswap.test')::jsonb, 'email', carol_auth::text, now(), now(), now()),
    (gen_random_uuid(), david_auth, format('{"sub":"%s","email":"%s"}', david_auth, 'david@skillswap.test')::jsonb, 'email', david_auth::text, now(), now(), now()),
    (gen_random_uuid(), emma_auth,  format('{"sub":"%s","email":"%s"}', emma_auth,  'emma@skillswap.test')::jsonb,  'email', emma_auth::text,  now(), now(), now()),
    (gen_random_uuid(), frank_auth, format('{"sub":"%s","email":"%s"}', frank_auth, 'frank@skillswap.test')::jsonb, 'email', frank_auth::text, now(), now(), now());

  -- Resolve the public.users ids created by the trigger.
  select id into admin_user from public.users where auth_id = admin_auth;
  select id into alice_user from public.users where auth_id = alice_auth;
  select id into bob_user   from public.users where auth_id = bob_auth;
  select id into carol_user from public.users where auth_id = carol_auth;
  select id into david_user from public.users where auth_id = david_auth;
  select id into emma_user  from public.users where auth_id = emma_auth;
  select id into frank_user from public.users where auth_id = frank_auth;

  ---------------------------------------------------------------------------
  -- 2. LOOKUP TABLES.
  ---------------------------------------------------------------------------
  insert into public.academic_levels (name_fr, name_en) values
    ('Licence 1', 'Bachelor Year 1'),
    ('Licence 3', 'Bachelor Year 3'),
    ('Master 1', 'Master Year 1'),
    ('Master 2', 'Master Year 2');

  select id into level_l1 from public.academic_levels where name_fr = 'Licence 1';
  select id into level_l3 from public.academic_levels where name_fr = 'Licence 3';
  select id into level_m1 from public.academic_levels where name_fr = 'Master 1';
  select id into level_m2 from public.academic_levels where name_fr = 'Master 2';

  insert into public.skills (name_fr, name_en) values
    ('JavaScript', 'JavaScript'),
    ('Python', 'Python'),
    ('Guitare', 'Guitar'),
    ('Prise de parole', 'Public Speaking'),
    ('Espagnol', 'Spanish'),
    ('Photographie', 'Photography'),
    ('Cuisine', 'Cooking'),
    ('Mathématiques', 'Mathematics');

  select id into skill_javascript from public.skills where name_fr = 'JavaScript';
  select id into skill_python from public.skills where name_fr = 'Python';
  select id into skill_guitar from public.skills where name_fr = 'Guitare';
  select id into skill_public_speaking from public.skills where name_fr = 'Prise de parole';
  select id into skill_spanish from public.skills where name_fr = 'Espagnol';
  select id into skill_photography from public.skills where name_fr = 'Photographie';
  select id into skill_cooking from public.skills where name_fr = 'Cuisine';
  select id into skill_mathematics from public.skills where name_fr = 'Mathématiques';

  insert into public.campuses (name_fr, name_en) values
    ('Campus de Paris', 'Paris Campus'),
    ('Campus de Lyon', 'Lyon Campus'),
    ('Campus de Lille', 'Lille Campus');

  select id into campus_paris from public.campuses where name_fr = 'Campus de Paris';
  select id into campus_lyon from public.campuses where name_fr = 'Campus de Lyon';
  select id into campus_lille from public.campuses where name_fr = 'Campus de Lille';

  insert into public.courses (name_fr, name_en) values
    ('Licence Informatique', 'Bachelor in Computer Science'),
    ('Master Data Science', 'Master in Data Science'),
    ('Licence Design', 'Bachelor in Design');

  select id into course_bachelor_cs from public.courses where name_fr = 'Licence Informatique';
  select id into course_master_data from public.courses where name_fr = 'Master Data Science';
  select id into course_bachelor_design from public.courses where name_fr = 'Licence Design';

  -- Session types are already seeded by the session_management migration.
  select id into type_workshop from public.session_types where name_fr = 'Atelier';
  select id into type_quick_course from public.session_types where name_fr = 'Cours rapide';
  select id into type_club from public.session_types where name_fr = 'Club thématique';

  ---------------------------------------------------------------------------
  -- 3. USER PROFILES (enrich the trigger-created rows + promote the admin).
  ---------------------------------------------------------------------------
  update public.users set first_name = 'Admin',  last_name = 'SkillSwap', phone = '+33600000001', academic_level_id = level_m2 where id = admin_user;
  update public.users set first_name = 'Alice',  last_name = 'Martin',    phone = '+33600000002', academic_level_id = level_l1 where id = alice_user;
  update public.users set first_name = 'Bob',    last_name = 'Durand',    phone = '+33600000003', academic_level_id = level_m1 where id = bob_user;
  update public.users set first_name = 'Carol',  last_name = 'Bernard',   phone = '+33600000004', academic_level_id = level_m2 where id = carol_user;
  update public.users set first_name = 'David',  last_name = 'Petit',     phone = '+33600000005', academic_level_id = level_l1 where id = david_user;
  update public.users set first_name = 'Emma',   last_name = 'Leroy',     phone = '+33600000006', academic_level_id = level_l3 where id = emma_user;
  update public.users set first_name = 'Frank',  last_name = 'Moreau',    phone = '+33600000007', academic_level_id = level_l3 where id = frank_user;

  update public.user_roles set role = 'ADMIN' where user_id = admin_user;

  ---------------------------------------------------------------------------
  -- 4. USER SKILLS (designed so learners 1–2 pair with teachers 7–9).
  ---------------------------------------------------------------------------
  insert into public.users_skills (user_id, skill_id, user_skill_level, user_skill_description) values
    -- Alice: teaches Guitar, wants JavaScript.
    (alice_user, skill_guitar,     9.0, 'Playing guitar for 8 years, happy to teach beginners.'),
    (alice_user, skill_javascript, 1.5, 'Just started learning to code, eager to improve.'),
    -- Bob: teaches JavaScript, wants Guitar.
    (bob_user,   skill_javascript, 8.5, 'Full-stack developer, comfortable with modern JS.'),
    (bob_user,   skill_guitar,     2.0, 'Total beginner, want to learn a few songs.'),
    -- Carol: teaches Python, wants Public Speaking.
    (carol_user, skill_python,        7.5, 'Data scientist, can teach Python from scratch.'),
    (carol_user, skill_public_speaking, 2.0, 'Nervous presenter, looking to gain confidence.'),
    -- David: teaches Public Speaking, wants Python.
    (david_user, skill_public_speaking, 8.0, 'Debate club captain, love coaching speakers.'),
    (david_user, skill_python,          1.0, 'Never coded before but very motivated.'),
    -- Emma: teaches Spanish, wants Photography.
    (emma_user,  skill_spanish,     9.5, 'Native Spanish speaker.'),
    (emma_user,  skill_photography, 1.5, 'Bought my first camera last month.'),
    -- Frank: teaches Photography, wants Spanish.
    (frank_user, skill_photography, 8.0, 'Semi-professional photographer.'),
    (frank_user, skill_spanish,     2.0, 'Know a few words, want to become conversational.'),
    -- Some extra breadth.
    (admin_user, skill_mathematics, 9.0, 'Happy to help with any math questions.'),
    (carol_user, skill_cooking,     6.0, 'Enjoy cooking on weekends.');

  ---------------------------------------------------------------------------
  -- 5. USER CAMPUSES (note: FK column is campus_id) — paired by campus.
  ---------------------------------------------------------------------------
  insert into public.users_campuses (user_id, campus_id) values
    (admin_user, campus_paris),
    (alice_user, campus_paris),
    (bob_user,   campus_paris),
    (carol_user, campus_lyon),
    (david_user, campus_lyon),
    (emma_user,  campus_lille),
    (frank_user, campus_lille);

  ---------------------------------------------------------------------------
  -- 6. USER COURSES (note: FK column is class_id).
  ---------------------------------------------------------------------------
  insert into public.users_courses (user_id, class_id, start_date, end_date) values
    (alice_user, course_bachelor_cs,     date '2025-09-01', date '2026-06-30'),
    (bob_user,   course_master_data,     date '2025-09-01', date '2026-06-30'),
    (carol_user, course_master_data,     date '2025-09-01', date '2026-06-30'),
    (david_user, course_bachelor_cs,     date '2025-09-01', date '2026-06-30'),
    (emma_user,  course_bachelor_design, date '2025-09-01', date '2026-06-30'),
    (frank_user, course_bachelor_design, date '2025-09-01', date '2026-06-30');

  ---------------------------------------------------------------------------
  -- 7. USER AVAILABILITIES (weekly recurring + one-off slots).
  ---------------------------------------------------------------------------
  insert into public.users_availabilities (user_id, recurring_days, start_timestamp, end_timestamp) values
    (alice_user, array['MONDAY','WEDNESDAY']::public.week_day_type[], now() + interval '1 day',  now() + interval '1 day'  + interval '2 hours'),
    (bob_user,   array['TUESDAY','THURSDAY']::public.week_day_type[], now() + interval '2 days', now() + interval '2 days' + interval '3 hours'),
    (carol_user, array['FRIDAY']::public.week_day_type[],             now() + interval '3 days', now() + interval '3 days' + interval '2 hours'),
    (david_user, null,                                                now() + interval '4 days', now() + interval '4 days' + interval '1 hour'),
    (emma_user,  array['SATURDAY','SUNDAY']::public.week_day_type[],  now() + interval '5 days', now() + interval '5 days' + interval '4 hours'),
    (frank_user, array['WEDNESDAY']::public.week_day_type[],          now() + interval '6 days', now() + interval '6 days' + interval '2 hours');

  ---------------------------------------------------------------------------
  -- 8. FRIENDSHIPS (confirmed pairs + pending requests).
  ---------------------------------------------------------------------------
  insert into public.friend_pairs (requestor_user_id, receiver_user_id) values
    (alice_user, bob_user),
    (carol_user, david_user);

  insert into public.friend_requests (requestor_user_id, receiver_user_id) values
    (emma_user,  alice_user),
    (frank_user, carol_user);

  ---------------------------------------------------------------------------
  -- 9. MATCHING (requests + resolved history).
  ---------------------------------------------------------------------------
  insert into public.match_requests (requestor_user_id, target_user_id, skill_id, status, message)
  values (alice_user, bob_user, skill_javascript, 'PENDING', 'Hi Bob! Could you help me get started with JavaScript?')
  returning id into match_request_alice_bob;

  insert into public.match_requests (requestor_user_id, target_user_id, skill_id, status, message)
  values (david_user, carol_user, skill_python, 'ACCEPTED', 'Would love to learn Python from you.')
  returning id into match_request_david_carol;

  insert into public.match_history (match_request_id, requestor_user_id, target_user_id, skill_id, outcome, rating, feedback)
  values (match_request_david_carol, david_user, carol_user, skill_python, 'COMPLETED', 5, 'Carol is an amazing and patient teacher!');

  ---------------------------------------------------------------------------
  -- 10. SESSIONS (+ participants) across statuses.
  ---------------------------------------------------------------------------
  insert into public.sessions (session_type_id, skill_id, organizer_user_id, campus_id, title, description, status, max_participants, location, start_timestamp, end_timestamp)
  values (type_workshop, skill_javascript, bob_user, campus_paris, 'Intro to JavaScript', 'A beginner-friendly workshop covering variables, functions and the DOM.', 'PLANNED', 8, 'Room B204', now() + interval '3 days', now() + interval '3 days' + interval '2 hours')
  returning id into session_js;

  insert into public.sessions (session_type_id, skill_id, organizer_user_id, campus_id, title, description, status, max_participants, location, start_timestamp, end_timestamp)
  values (type_quick_course, skill_public_speaking, david_user, campus_lyon, 'Public Speaking Basics', 'Conquer stage fright and structure a compelling talk.', 'COMPLETED', 6, 'Auditorium A', now() - interval '7 days', now() - interval '7 days' + interval '90 minutes')
  returning id into session_speaking;

  insert into public.sessions (session_type_id, skill_id, organizer_user_id, campus_id, title, description, status, max_participants, location, start_timestamp, end_timestamp)
  values (type_club, skill_spanish, emma_user, campus_lille, 'Spanish Conversation Club', 'Weekly informal Spanish conversation practice over coffee.', 'PLANNED', 12, 'Cafeteria', now() + interval '5 days', now() + interval '5 days' + interval '2 hours')
  returning id into session_spanish;

  insert into public.session_participants (session_id, user_id, role) values
    (session_js, bob_user, 'ORGANIZER'),
    (session_js, alice_user, 'LEARNER'),
    (session_speaking, david_user, 'ORGANIZER'),
    (session_speaking, carol_user, 'LEARNER'),
    (session_spanish, emma_user, 'ORGANIZER'),
    (session_spanish, frank_user, 'LEARNER');

  ---------------------------------------------------------------------------
  -- 11. GAMIFICATION: badges, point actions, challenges.
  ---------------------------------------------------------------------------
  insert into public.badges (name_fr, name_en, description_fr, description_en, criteria_description, points_reward) values
    ('Premiers pas', 'First Steps', 'Compléter votre première session.', 'Complete your first session.', 'sessions:1', 20),
    ('Esprit d''équipe', 'Team Player', 'Ajouter votre premier ami.', 'Add your first friend.', 'friends:1', 15),
    ('Partageur de savoir', 'Knowledge Sharer', 'Enseigner 5 sessions.', 'Teach 5 sessions.', 'sessions:5', 100),
    ('Maître des points', 'Point Master', 'Atteindre 500 points.', 'Reach 500 points.', 'points:500', 0);

  select id into badge_first_steps from public.badges where name_en = 'First Steps';
  select id into badge_team_player from public.badges where name_en = 'Team Player';
  select id into badge_knowledge_sharer from public.badges where name_en = 'Knowledge Sharer';
  select id into badge_point_master from public.badges where name_en = 'Point Master';

  insert into public.point_actions (action_key, name_fr, name_en, points_value) values
    ('session_completed_as_teacher', 'Session enseignée', 'Session taught', 50),
    ('session_completed_as_learner', 'Session suivie', 'Session attended', 30),
    ('challenge_completed', 'Défi complété', 'Challenge completed', 100),
    ('post_created', 'Publication créée', 'Post created', 10),
    ('friend_added', 'Ami ajouté', 'Friend added', 15);

  select id into action_session_teacher from public.point_actions where action_key = 'session_completed_as_teacher';
  select id into action_session_learner from public.point_actions where action_key = 'session_completed_as_learner';
  select id into action_challenge_done from public.point_actions where action_key = 'challenge_completed';
  select id into action_post_created from public.point_actions where action_key = 'post_created';
  select id into action_friend_added from public.point_actions where action_key = 'friend_added';

  insert into public.challenges (name_fr, name_en, description_fr, description_en, goal_type, goal_count, points_reward, badge_reward_id, start_date, end_date) values
    ('Marathon d''apprentissage', 'Learning Marathon', 'Compléter 3 sessions.', 'Complete 3 sessions.', 'session_completed_as_learner', 3, 100, badge_knowledge_sharer, current_date - 10, current_date + 30),
    ('Réseau social', 'Social Butterfly', 'Ajouter 5 amis.', 'Add 5 friends.', 'friend_added', 5, 75, null, current_date - 5, current_date + 30);

  select id into challenge_three_sessions from public.challenges where name_en = 'Learning Marathon';
  select id into challenge_five_friends from public.challenges where name_en = 'Social Butterfly';

  ---------------------------------------------------------------------------
  -- 12. GAMIFICATION: ledger entries, earned badges, challenge progress.
  ---------------------------------------------------------------------------
  insert into public.user_points_ledger (user_id, point_action_id, points_earned, reference_id) values
    (david_user, action_session_learner, 30, session_speaking),
    (carol_user, action_session_teacher, 50, session_speaking),
    (carol_user, action_friend_added, 15, null),
    (david_user, action_friend_added, 15, null),
    (alice_user, action_post_created, 10, null),
    (bob_user,   action_post_created, 10, null),
    (carol_user, action_challenge_done, 100, challenge_three_sessions);

  insert into public.user_badges (user_id, badge_id) values
    (david_user, badge_first_steps),
    (carol_user, badge_first_steps),
    (carol_user, badge_team_player),
    (david_user, badge_team_player);

  insert into public.user_challenges (user_id, challenge_id, current_progress, status, completed_at) values
    (carol_user, challenge_three_sessions, 3, 'COMPLETED', now() - interval '2 days'),
    (david_user, challenge_three_sessions, 1, 'IN_PROGRESS', null),
    (alice_user, challenge_five_friends, 1, 'IN_PROGRESS', null),
    (carol_user, challenge_five_friends, 1, 'IN_PROGRESS', null);

  ---------------------------------------------------------------------------
  -- 13. SOCIAL FEED: posts, likes, comments, shares.
  ---------------------------------------------------------------------------
  insert into public.posts (author_user_id, post_type, visibility, title, content, referenced_session_id)
  values (alice_user, 'ACHIEVEMENT', 'PUBLIC', 'Wrote my first function!', 'Thanks to Bob''s upcoming workshop prep, I finally understood JavaScript functions. So excited!', null)
  returning id into post_alice;

  insert into public.posts (author_user_id, post_type, visibility, title, content, referenced_user_ids)
  values (carol_user, 'RECOMMENDATION', 'PUBLIC', 'Highly recommend David', 'If you struggle with public speaking, David is the person to talk to. Patient and encouraging.', array[david_user])
  returning id into post_carol;

  insert into public.posts (author_user_id, post_type, visibility, title, content, referenced_session_id)
  values (david_user, 'FEEDBACK', 'PUBLIC', 'Great Python session', 'Carol made Python click for me in a single session. Looking forward to the next one!', null)
  returning id into post_david;

  insert into public.posts (author_user_id, post_type, visibility, title, content)
  values (emma_user, 'ACHIEVEMENT', 'FRIENDS_ONLY', 'Spanish club is growing', 'Our little Spanish conversation club now has a dozen regulars. Friends only update :)')
  returning id into post_emma;

  insert into public.post_likes (post_id, user_id) values
    (post_alice, bob_user),
    (post_alice, carol_user),
    (post_carol, david_user),
    (post_carol, alice_user),
    (post_david, carol_user);

  insert into public.post_comments (post_id, author_user_id, content) values
    (post_alice, bob_user, 'So proud of you Alice! See you at the workshop.'),
    (post_carol, david_user, 'Thank you Carol, that means a lot!'),
    (post_david, carol_user, 'You did all the hard work, David!');

  insert into public.post_shares (original_post_id, sharing_user_id, comment) values
    (post_carol, alice_user, 'Seconding this — David is great.');

  ---------------------------------------------------------------------------
  -- 14. NOTIFICATIONS (i18n key based, mix of read/unread).
  ---------------------------------------------------------------------------
  insert into public.notifications (recipient_user_id, sender_user_id, notification_type, title_key, body_key, reference_id, reference_type, is_read) values
    (bob_user,   alice_user, 'MATCH_REQUEST',       'New match request', 'Alice would like to learn JavaScript with you.', match_request_alice_bob, 'match_request', false),
    (alice_user, emma_user,  'FRIEND_REQUEST',      'New friend request', 'Emma sent you a friend request.', null, 'friend_request', false),
    (carol_user, null,       'CHALLENGE_COMPLETED', 'Challenge completed!', 'You completed the Learning Marathon challenge.', challenge_three_sessions, 'challenge', true),
    (david_user, null,       'BADGE_EARNED',        'Badge earned', 'You earned the First Steps badge.', badge_first_steps, 'badge', false),
    (alice_user, bob_user,   'POST_LIKE',           'Someone liked your post', 'Bob liked your achievement post.', post_alice, 'post', true),
    (alice_user, admin_user, 'ADMIN_BROADCAST',     'Welcome to SkillSwap', 'Complete your profile to get better match suggestions!', null, null, false),
    (frank_user, admin_user, 'ADMIN_BROADCAST',     'Welcome to SkillSwap', 'Complete your profile to get better match suggestions!', null, null, false);

  ---------------------------------------------------------------------------
  -- 15. ADMIN: a pending content report for the moderation queue.
  ---------------------------------------------------------------------------
  insert into public.content_reports (reporter_user_id, reported_entity_id, reported_entity_type, reason, status) values
    (frank_user, post_emma, 'post', 'This post seems off-topic for the public feed.', 'PENDING');

end $$;
